.PHONY: clean All

All:
	@echo "----------Building project:[ q2 - Debug ]----------"
	@cd "C:\Users\rtopa\repo\cplus-learn\practice\p3\q2\q2" && "$(MAKE)" -f  "q2.mk"
clean:
	@echo "----------Cleaning project:[ q2 - Debug ]----------"
	@cd "C:\Users\rtopa\repo\cplus-learn\practice\p3\q2\q2" && "$(MAKE)" -f  "q2.mk" clean
